language: node_js
cache:
  directories:
    - node_modules
node_js:
  - "8"
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
script:
  - npm run test
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
  - greenkeeper-lockfile-upload
branches:
  only:
    - master
    - /^greenkeeper/.*$/
