language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script:
  - npm prune
  - greenkeeper-lockfile-update
script:
  - npm run lint
  - npm run test
after_script: greenkeeper-lockfile-upload
after_success:
  - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release
branches:
  only:
    - master
    - /^greenkeeper/.*$/