module.exports = {
  rules: {
    'block-spacing': [2, 'always'],
    'brace-style': [2, '1tbs', { allowSingleLine: true }],
    camelcase: [2, { properties: 'never' }],
    'comma-spacing': [2, { before: false, after: true }],
    'comma-style': [2, 'last'],
    'computed-property-spacing': [2, 'never'],
    'eol-last': 2,
    'func-names': 1,
    indent: [2, 2, { SwitchCase: 1, VariableDeclarator: 1 }],
    'keyword-spacing': [
      2,
      {
        before: true,
        after: true,
        overrides: {
          return: { after: true },
          throw: { after: true },
          case: { after: true },
        },
      },
    ],
    'max-len': [
      1,
      80,
      2,
      {
        ignoreUrls: true,
        ignoreComments: true,
        ignoreStrings: true,
        ignoreTemplateLiterals: true,
        ignoreRegExpLiterals: true,
      },
    ],
    'max-statements-per-line': [0, { max: 1 }],
    'new-cap': [2, { capIsNewExceptions: ['Router'] }],
    'newline-per-chained-call': [2, { ignoreChainWithDepth: 3 }],
    'no-array-constructor': 2,
    'no-mixed-spaces-and-tabs': 2,
    'no-new-object': 2,
    'no-spaced-func': 2,
    'no-trailing-spaces': 2,
    'no-unneeded-ternary': [2, { defaultAssignment: false }],
    'no-whitespace-before-property': 2,
    'object-curly-spacing': [2, 'always'],
    'padded-blocks': [2, 'never'],
    'quote-props': [
      2,
      'as-needed',
      { keywords: false, unnecessary: true, numbers: false },
    ],
    quotes: [2, 'single', 'avoid-escape'],
    'semi-spacing': [2, { before: false, after: true }],
    semi: [2, 'always'],
    'space-before-blocks': 2,
    'space-before-function-paren': [2, { anonymous: 'always', named: 'never' }],
    'space-infix-ops': 2,
  },
};
